version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: albumstore
      MYSQL_DATABASE: albumstore
      MYSQL_USER: albumstore
      MYSQL_PASSWORD: '!@12QWqw'
    ports:
      - "3306:3306"