version: 2
jobs:
  build:
    working_directory: ~/albumstore
    docker:
      - image: maven:3.6-jdk-11-slim
        environment:
          #### MYSQL ####
          MYSQL_USER: albumstore
          MYSQL_PASSWORD: '!@12QWqw'
          MYSQL_DATABASE: albumstore
          MYSQL_PORT: 3306
          MYSQL_HOST: localhost
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: albumstore
          MYSQL_DATABASE: albumstore
          MYSQL_USER: albumstore
          MYSQL_PASSWORD: '!@12QWqw'

    steps:

      - checkout

      - restore_cache:
          key: albumstore-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: albumstore-{{ checksum "pom.xml" }}

      - run: mvn clean install

      - store_artifacts:
          path: target/albumstore*.jar

    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples